window.PRODUCTS = [
  {
    id: "rose-saffron",
    path: "rose-saffron.html",
    name: "Rose and Saffron Serum",
    tagline: "Floral glow with a silky finish",
    description:
      "A botanical facial serum infused with rose and saffron notes to support a soft, radiant finish.",
    longDescription:
      "Rose and Saffron Serum is designed for customers who want a refined glow ritual with a soft floral character. It layers easily into both morning and evening routines and feels especially fitting for gifting or vanity display.",
    price: 2450,
    badge: "Bestseller",
    rating: "4.9",
    size: "30ml bottle",
    category: ["bestseller", "skin-soothing", "serum", "featured"],
    notes: ["Glow care", "Floral", "Daily ritual"],
    collection: "Glow Care",
    benefits: ["Radiance support", "Light layering", "Gift-friendly"],
    ritual:
      "Apply after cleansing and before moisturizer as part of a morning or evening glow routine.",
    ingredients: ["Rose-inspired care", "Saffron notes", "Botanical hydration"],
    color: "linear-gradient(160deg, #d78f8b, #b85c38)",
  },
  {
    id: "neem-garden",
    path: "neem-garden.html",
    name: "Neem Garden Face Wash",
    tagline: "Clarifying care for everyday skin",
    description:
      "Neem, basil, and gentle cleansing agents come together in a crisp herbal wash suited for humid days and active routines.",
    longDescription:
      "Neem Garden Face Wash gives the lineup a cleaner, herbal side. It suits customers who prefer refreshing rinses and a more clarified post-cleanse feel, especially in warm weather or oily-skin routines.",
    price: 1650,
    badge: "Purifying",
    rating: "4.8",
    size: "120ml bottle",
    category: ["bestseller", "skin-soothing", "oily-skin", "featured"],
    notes: ["Herbal", "Fresh", "Face wash"],
    collection: "Clarifying Care",
    benefits: ["Fresh rinse", "Daily use", "Humid-weather friendly"],
    ritual:
      "Use as a morning or evening cleanser when you want a fresher, more clarified feeling finish.",
    ingredients: ["Neem-led care", "Basil character", "Gentle cleansing base"],
    color: "linear-gradient(160deg, #8f9d75, #617154)",
  },
  {
    id: "milk-honey",
    path: "milk-honey.html",
    name: "Milk and Honey Soap Bar",
    tagline: "Comforting moisture for dry skin",
    description:
      "A creamy blend of oat milk and honey fragrance crafted to leave the skin feeling comforted and supple.",
    longDescription:
      "Milk and Honey Soap Bar is one of the softest entries in the range. It is built for customers who want comforting texture, a creamy lather, and a more nurturing daily bathing experience.",
    price: 1380,
    badge: "Gentle",
    rating: "4.7",
    size: "110g bar",
    category: ["skin-soothing", "featured"],
    notes: ["Creamy", "Comforting", "Dry skin"],
    collection: "Comfort Ritual",
    benefits: ["Creamy lather", "Dry-skin friendly", "Soft finish"],
    ritual:
      "Use during slower evening showers or whenever the skin needs a softer, more comforting cleanse.",
    ingredients: ["Oat milk feel", "Honey-inspired warmth", "Creamy soap base"],
    color: "linear-gradient(160deg, #ebd4a1, #cba35e)",
  },
  {
    id: "lavender-silk",
    path: "lavender-silk.html",
    name: "Lavender Silk Shampoo",
    tagline: "Evening calm with a soft herbal rinse",
    description:
      "A calming botanical shampoo with lavender character and a soft clean rinse for unhurried hair rituals.",
    longDescription:
      "Lavender Silk Shampoo brings the brand into hair care with a more relaxed, evening-ritual energy. It is suited to customers who want a gentler-feeling cleanse and a calmer shower experience.",
    price: 1980,
    badge: "Calming",
    rating: "4.8",
    size: "220ml bottle",
    category: ["haircare", "featured"],
    notes: ["Lavender", "Hair care", "Soft rinse"],
    collection: "Hair Ritual",
    benefits: ["Soft rinse", "Calming scent", "Hair-care staple"],
    ritual:
      "Massage into wet hair as part of a slower shower routine, then rinse for a clean but gentle finish.",
    ingredients: ["Lavender character", "Botanical shampoo base", "Soft-rinse feel"],
    color: "linear-gradient(160deg, #a28bb1, #765d86)",
  },
  {
    id: "signature-box",
    path: "signature-box.html",
    name: "Signature Care Box",
    tagline: "Soap, serum, and hair care wrapped for gifting",
    description:
      "A curated gift-ready set with signature soaps, serum, shampoo, and botanical cards in a keepsake presentation box.",
    longDescription:
      "Signature Care Box is the brand's most complete gifting expression. It is ideal for birthdays, bridal hampers, hosting gifts, or anyone who wants to experience multiple categories at once.",
    price: 7200,
    badge: "Gift Edit",
    rating: "5.0",
    size: "4-piece set",
    category: ["gifting", "bestseller", "featured"],
    notes: ["Ribbon wrapped", "Skincare", "Bridal hampers"],
    collection: "Gifting",
    benefits: ["Multi-category edit", "Gift-ready presentation", "Premium keepsake feel"],
    ritual:
      "Use as a complete care gift or split across bath, skin, and hair rituals over the week.",
    ingredients: ["Soap selection", "Serum inclusion", "Shampoo ritual"],
    color: "linear-gradient(160deg, #8c6470, #5d3d49)",
  },
  {
    id: "mini-discovery",
    path: "mini-discovery.html",
    name: "Mini Discovery Set",
    tagline: "A starter edit across skin and hair care",
    description:
      "A lower-commitment set designed to help new customers sample bestselling soap, serum, and shampoo formulas before choosing full sizes.",
    longDescription:
      "Mini Discovery Set lowers the entry point for first-time customers. It is especially useful for gifting, travel, or anyone who wants to test the brand's skin and hair range before committing.",
    price: 3150,
    badge: "Starter Set",
    rating: "4.8",
    size: "3 mini essentials",
    category: ["gifting", "featured"],
    notes: ["Trial size", "Travel", "Skin + hair"],
    collection: "Discovery",
    benefits: ["Trial-friendly", "Travel-ready", "Multi-category sampler"],
    ritual:
      "Use across a few days to experience the brand's signature skin and hair rituals in smaller sizes.",
    ingredients: ["Soap sample", "Serum sample", "Shampoo sample"],
    color: "linear-gradient(160deg, #c5926a, #8c5f3d)",
  },
  {
    id: "argan-repair",
    path: "argan-repair.html",
    name: "Argan Repair Shampoo",
    tagline: "Botanical care for dry or tired hair",
    description:
      "An argan-led shampoo designed to leave hair feeling smoother, cleaner, and more manageable after each wash.",
    longDescription:
      "Argan Repair Shampoo is aimed at customers who want a richer hair-care option within the range. It balances a cleaner rinse with a smoother after-feel and fits well into repair-focused routines.",
    price: 2140,
    badge: "Hair Hero",
    rating: "4.7",
    size: "220ml bottle",
    category: ["haircare", "featured"],
    notes: ["Argan", "Repair", "Hair care"],
    collection: "Hair Ritual",
    benefits: ["Smoother feel", "Manageability", "Repair-focused wash"],
    ritual:
      "Use during wash days when the hair needs a richer cleanse and a smoother post-rinse finish.",
    ingredients: ["Argan-led care", "Botanical shampoo base", "Repair ritual"],
    color: "linear-gradient(160deg, #b78b62, #80553b)",
  },
  {
    id: "saffron-bright",
    path: "saffron-bright.html",
    name: "Saffron Bright Face Wash",
    tagline: "A daily wash for a fresher-looking finish",
    description:
      "A saffron-inspired face wash built for daily use, with a cleaner rinse and a bright, botanical feel.",
    longDescription:
      "Saffron Bright Face Wash gives the facial-cleansing lineup a more luminous personality. It suits daily use and appeals to customers who want brightness cues without leaving the routine feeling harsh.",
    price: 1720,
    badge: "Glow Wash",
    rating: "4.8",
    size: "120ml bottle",
    category: ["skin-soothing", "oily-skin", "featured"],
    notes: ["Saffron", "Face wash", "Bright finish"],
    collection: "Glow Care",
    benefits: ["Daily cleanse", "Bright-feel finish", "Botanical profile"],
    ritual:
      "Use in the morning for a fresher start or at night as part of a glow-focused cleansing ritual.",
    ingredients: ["Saffron-inspired care", "Gentle wash base", "Bright finish"],
    color: "linear-gradient(160deg, #c5926a, #8c5f3d)",
  },
  {
    id: "sage-alpha",
    path: "sage-alpha.html",
    name: "Sage Alpha Serum",
    tagline: "Barrier support with a smoother finish",
    description:
      "A daily serum designed to support hydration and leave skin looking calmer and more balanced.",
    longDescription:
      "Sage Alpha Serum is positioned for customers who want a dependable daily serum with a barrier-supporting profile. It fits well into minimal routines and calmer skin-care rituals.",
    price: 2100,
    badge: "Sale",
    rating: "4.8",
    size: "30ml bottle",
    category: ["serum"],
    notes: ["Barrier care", "Hydration", "Serum"],
    collection: "Serum Studio",
    benefits: ["Hydration support", "Balanced finish", "Easy layering"],
    ritual:
      "Apply after cleansing and before moisturizer in routines focused on calm, hydrated-looking skin.",
    ingredients: ["Hydration support", "Barrier-focused feel", "Daily layering"],
    color: "linear-gradient(160deg, #b28062, #7b5442)",
  },
  {
    id: "sage-glow",
    path: "sage-glow.html",
    name: "Sage Glow Serum",
    tagline: "Brightening care for a fresher finish",
    description:
      "A radiance-focused serum made for customers who want a smoother, brighter everyday ritual.",
    longDescription:
      "Sage Glow Serum is the more luminous option in the serum lineup. It is made for routines that prioritize brightness, freshness, and a visibly polished final step.",
    price: 2200,
    badge: "Sale",
    rating: "4.8",
    size: "30ml bottle",
    category: ["serum"],
    notes: ["Brightening", "Glow", "Serum"],
    collection: "Serum Studio",
    benefits: ["Bright finish", "Everyday glow", "Smooth layering"],
    ritual:
      "Use after cleansing whenever the routine calls for a brighter, more polished serum step.",
    ingredients: ["Glow-focused care", "Radiance profile", "Daily serum base"],
    color: "linear-gradient(160deg, #d6b18c, #8f6246)",
  },
  {
    id: "sage-calm",
    path: "sage-calm.html",
    name: "Sage Calm Serum",
    tagline: "Hydrating support for sensitive-feeling skin",
    description:
      "A calming serum that layers easily into evening routines and helps skin feel replenished.",
    longDescription:
      "Sage Calm Serum is the softer, more comfort-led option within the serum range. It fits particularly well into evening routines or gentler regimens where replenishment is the goal.",
    price: 2100,
    badge: "Sale",
    rating: "4.7",
    size: "30ml bottle",
    category: ["serum"],
    notes: ["Calming", "Hydration", "Serum"],
    collection: "Serum Studio",
    benefits: ["Comfort-first feel", "Evening layering", "Hydration support"],
    ritual:
      "Layer into evening routines after cleansing to support a calmer, replenished skin feel.",
    ingredients: ["Hydration support", "Calming profile", "Soft evening ritual"],
    color: "linear-gradient(160deg, #9c886e, #5f4d3c)",
  },
  {
    id: "charcoal-bar",
    path: "charcoal-bar.html",
    name: "Charcoal Detox Bar",
    tagline: "Deep-clean feel for oily or breakout-prone skin",
    description:
      "A detoxifying soap bar that supports a cleaner finish when the skin needs a more purifying wash.",
    longDescription:
      "Charcoal Detox Bar speaks to customers who want a stronger-feeling cleanse in soap form. It fits oily-skin routines, detox-focused edits, and face-and-body use where freshness matters.",
    price: 1270,
    badge: "Sale",
    rating: "4.7",
    size: "100g bar",
    category: ["oily-skin"],
    notes: ["Charcoal", "Detox", "Soap"],
    collection: "Oily Skin",
    benefits: ["Purifying feel", "Soap format", "Fresh finish"],
    ritual:
      "Use during face-and-body routines when a more detox-focused, cleaner-feeling wash is preferred.",
    ingredients: ["Charcoal profile", "Soap cleanse", "Detox ritual"],
    color: "linear-gradient(160deg, #7e7b75, #4f4d49)",
  },
  {
    id: "tea-tree-bar",
    path: "tea-tree-bar.html",
    name: "Tea Tree Purifying Bar",
    tagline: "Fresh herbal cleansing for daily reset",
    description:
      "Tea tree and crisp botanicals come together in a face-and-body bar suited to oily skin routines.",
    longDescription:
      "Tea Tree Purifying Bar is made for customers who like a brisk, herbal kind of freshness. It works well for daily oily-skin resets and customers who prefer bar-based cleansing over bottles.",
    price: 1310,
    badge: "Sale",
    rating: "4.8",
    size: "100g bar",
    category: ["oily-skin"],
    notes: ["Tea tree", "Purifying", "Soap"],
    collection: "Oily Skin",
    benefits: ["Fresh reset", "Herbal profile", "Daily bar cleanse"],
    ritual:
      "Use as part of a quick daily reset whenever the skin needs a fresher, more herbal-feeling cleanse.",
    ingredients: ["Tea tree profile", "Botanical soap base", "Purifying ritual"],
    color: "linear-gradient(160deg, #b6b754, #7a7b2a)",
  },
];
